### ISSUE TITLE
logging inside the app

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/NEST-roadmap#1]
Research & implementation of the logging feature inside `teal` app:

Research:

- [x] https://github.com/insightsengineering/teal.devel/issues/34

Engine implementation:

- [x] https://github.com/insightsengineering/coredev-tasks/issues/52
- [x] https://github.com/insightsengineering/teal/issues/318
- [x] https://github.com/insightsengineering/teal/issues/319

Actual logs:

- [x] https://github.com/insightsengineering/teal/issues/322
- [x] https://github.com/insightsengineering/teal.devel/issues/127
- [x] https://github.com/insightsengineering/teal/issues/323
- [x] https://github.com/insightsengineering/teal/issues/375
- [x] https://github.com/insightsengineering/coredev-tasks/issues/54
- [x] https://github.com/insightsengineering/teal/issues/324
- [x] https://github.com/insightsengineering/teal.modules.general/issues/224
- ~~https://github.com/insightsengineering/teal.modules.general/issues/239~~
- [x] https://github.com/insightsengineering/teal.modules.clinical/issues/192
- ~~https://github.com/insightsengineering/teal.modules.clinical/issues/227~~
- [x] https://github.com/insightsengineering/coredev-tasks/issues/72
- [x] https://github.com/insightsengineering/teal.osprey/issues/76
- [x] https://github.com/insightsengineering/teal.goshawk/issues/91
- [x] https://github.com/insightsengineering/teal.modules.hermes/issues/189
- [x] https://github.com/insightsengineering/teal.devel/issues/200
- [x] https://github.com/insightsengineering/teal.devel/issues/184

Documentation:

- [x] https://github.com/insightsengineering/coredev-tasks/issues/53
- [x] https://github.com/insightsengineering/coredev-tasks/issues/66

**Comment by donyunardi** [comment]
Continue with #74.
Closing.
