### ISSUE TITLE
API simplification

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/NEST-roadmap#2]
Here is the list of planned actions (don't confuse with suggestions). This list might grow once we agree on other "unresolved" yet parts of the teal. The whole point of this milestone is to simplify API by:
- making it easy to call the teal app.
- making it easy to apply teal components to any shiny app.
 
## 1. Simplify teal components

![Image](https://user-images.githubusercontent.com/6959016/173343033-271dd657-58fe-4117-83ed-a00b4e539a3a.jpg)

Final objective for first iteration of the API simplification is to call following module:
```r
tm_module_srv <- function(data <list of reactives or list of data.frames>, filter_panel <filterPanelAPI>) {
  initial_chunks <- reactive({
    chunks_new(env = data, expr = get_expr(data))
  })
  ...
  extracts <- data_extract_srv(data, ...)
  merged_call <- data_merge_srv(extracts, get_join_keys(data), ...)
  
  another_chunk <- reactive({
    chunks_push(merged_call())
  })
  ...
  
  show_rcode(expr = final_chunk$get_expr())
}
```

To allow above model, we need to provide list of data.frames (or MAE) to `data` argument instead of passing datasets (FilteredData)
```r
# somewhere in teal::init
data <- lapply(<module datanames>, FilteredData$get_reactive_data)
```

Another objective is to remove TealData frrom FilteredData dependencies.
- FIlteredData should not depend on the TealData/TealDataset.
- teal_module(s) should not depend on the FIlteredData

During the refactor we need to make sure that we won't break everything. I suggest to still send `FilteredData` if the `datasets` argument is used in the module. 

- [x] https://github.com/insightsengineering/teal.widgets/issues/30
- [x] https://github.com/insightsengineering/teal.slice/issues/33
- Remove teal.transform dependency on the FilteredData and chunks
  - [x] https://github.com/insightsengineering/teal.transform/issues/61
  - [x] https://github.com/insightsengineering/teal.transform/issues/67
  - [x] https://github.com/insightsengineering/teal.transform/issues/68
- [x] https://github.com/insightsengineering/teal/issues/654
- [x] ~~https://github.com/insightsengineering/teal.code/issues/32~~
- Don't use datasets argument anymore
  - [x] https://github.com/insightsengineering/teal.modules.general/issues/402
  - [x] https://github.com/insightsengineering/teal.modules.clinical/issues/488
  - [x] https://github.com/insightsengineering/teal.osprey/issues/145
  - [x] https://github.com/insightsengineering/teal.goshawk/issues/152
  - [x] https://github.com/insightsengineering/teal.modules.hermes/issues/247
- ~~https://github.com/insightsengineering/teal/issues/656~~
- [x] https://github.com/insightsengineering/teal.slice/issues/64
- ~~https://github.com/insightsengineering/teal/issues/678~~

**Comment by donyunardi** [comment]
Move insightsengineering/teal/issues/656 and insightsengineering/teal/issues/678 to #50 
Closing.
