### ISSUE TITLE
Creating a new `nestcolor` package to help define a set of colors and color palette for plotting

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/NEST-roadmap#39]
- [x] https://github.com/insightsengineering/coredev-tasks/issues/295
- [x] https://github.com/insightsengineering/coredev-tasks/issues/289
- [ ] add into all renv/yamls
- [x] https://github.com/insightsengineering/coredev-tasks/issues/293
- [x] https://github.com/insightsengineering/coredev-tasks/issues/291
- [x] https://github.com/insightsengineering/coredev-tasks/issues/294
- [x] https://github.com/insightsengineering/tern/issues/595
- [x] https://github.com/insightsengineering/coredev-tasks/issues/290
- [x] https://github.com/insightsengineering/teal.modules.clinical/issues/511
- [x] https://github.com/insightsengineering/teal.modules.general/issues/416
- [x] https://github.com/insightsengineering/osprey/issues/91
- [x] https://github.com/insightsengineering/teal.osprey/issues/156
- [x] https://github.com/insightsengineering/goshawk/issues/159
- [x] https://github.com/insightsengineering/teal.goshawk/issues/161

**Comment by gogonzo** [comment]
We decided with @shajoezhu that we will focus more on `nestcolors` package alone to produce necessary convenient function to avoid reverting changes in the downstream packages (modules).

Some packages doesn't have any color management (tmg), some have `var`, `col` (osprey) mapping which goes to scale_color_manual and `goshawk` has a argument for treatment coloring which requires a named list. 
We need to find the optimal solution here. Good benchmark is for [example](https://github.com/ModelOriented/DALEX/blob/master/R/misc_theme_drwhy.R).

We probably need some option to change the default ggplot pallette, some predefined `scale_color_` and convenient functions to easily map vector to a colors.

**Comment by gogonzo** [comment]
We are still in the research phase as we don't know how complex it might be to change the color pallette of all NEST modules. There is a way of fixing ggplot default colors by options but not for all plots, because:
- some of the plots are not ggplot2
- some of the plots have "hardcoded" colors matched
- other modules probably can be updated automatically with options

**Comment by gogonzo** [comment]
Closing as all sub-issues have been addressed
