### ISSUE TITLE
Simplify Chunks - implement quosure

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/NEST-roadmap#45]
- [x] https://github.com/insightsengineering/teal.code/issues/34
- [x] https://github.com/insightsengineering/teal.code/issues/26
- [x] Implement new chunks in the tlg modules:
    - [x] https://github.com/insightsengineering/teal.modules.general/issues/388
    - [x] https://github.com/insightsengineering/teal.modules.clinical/issues/479
    - [x] https://github.com/insightsengineering/teal.goshawk/issues/146
    - [x] https://github.com/insightsengineering/teal.osprey/issues/141
- [x] https://github.com/insightsengineering/teal/issues/640
- [ ] **Issues found during the implementation:**
    - [ ] ~~https://github.com/insightsengineering/teal.code/issues/57~~
    - [ ] ~~https://github.com/insightsengineering/teal.code/issues/56~~
    - [x] https://github.com/insightsengineering/teal/issues/640
    - [ ] ~~https://github.com/insightsengineering/teal.slice/issues/84~~
    - [x] https://github.com/insightsengineering/teal/issues/722
    - [x] https://github.com/insightsengineering/teal.code/issues/59
    - [ ] ~~https://github.com/insightsengineering/teal.code/issues/63~~

**Comment by donyunardi** [comment]
We will continue with #69
