### ISSUE TITLE
Improve UI of filter panel (2)

### ISSUE THREAD

**Issue by kumamiao** [insightsengineering/NEST-roadmap#46]
Re-design filter panel, see list below on individual issue

**Comment by gogonzo** [comment]
This roadmap card will be for the design phase of the new Filter Panel:

### Design
- [x] design 1 https://github.com/insightsengineering/teal.slice/issues/47
- [x] design 2
    -  Compile all the comments that was mentioned in design 1 issue.
    - The team will meet three times during Week 43, 45, 47, and 49 (increment 5) to further discuss technical objectives to achieve user requirements.
    - GitHub comments might not be the best place to capture all the ideas and putting things in internal gDoc also not shareable with external collaborators. Need to find out other alternatives to enable external collaborators to participate in the design phase. (Task for @donyunardi). UPDATE: Internal gDoc can be shared with external collaborator. If the gDoc is in a shared folder, then it depends on the folder setup and restriction. We'll continue to use gDoc for now.

The following issues should be consider during the design process:
- [x] https://github.com/insightsengineering/teal.slice/issues/13
- [x] https://github.com/insightsengineering/teal.slice/issues/14
- [ ] ~~https://github.com/insightsengineering/teal.slice/issues/6~~
- [x] https://github.com/insightsengineering/teal.slice/issues/84
- [ ] ~~https://github.com/insightsengineering/teal.slice/issues/72~~


We have created an issue milestone to track implementation progress:
https://github.com/insightsengineering/teal.slice/milestone/1

**Comment by lcd2yyz** [comment]
Continuing implementation of the new design in the new increment (https://github.com/insightsengineering/NEST-roadmap/issues/81)
