### ISSUE TITLE
Improve UI of teal apps

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/NEST-roadmap#48]
- [x] https://github.com/insightsengineering/teal/issues/669
- [x] https://github.com/insightsengineering/teal/issues/652
- [x] https://github.com/insightsengineering/teal/issues/534
- [x] https://github.com/insightsengineering/teal/issues/667
- [ ] https://github.com/insightsengineering/teal.modules.general/issues/62 This is an old issue, need to refine?

Question for refinement discussion:
Does teal UI improvement is closely related with filter panel redesign or can we work on them separately?
If the latter, which one that we should do first?

**Comment by pawelru** [comment]
I am going to close this one. It's not well refined as an epic. Let's process child tasks separately
