### ISSUE TITLE
Improve UI for modules selection

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/NEST-roadmap#56]
Implement panel to include arguments - start with the simple scenarios. Don't go to deep into data_extract/etc

![image](https://user-images.githubusercontent.com/6959016/176633193-f05395c4-c102-41cd-b0c1-3e861026dc1d.png)

**Comment by donyunardi** [comment]
As discussed in refinement meeting on 11AUG22, I'm closing the issue because we don't need to do the argument for the marketplace (for now).

The current requirement is to enable user to select modules and to generate the teal files (app.R) without arguments.
