### ISSUE TITLE
Research rhino for teal skeleton 

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/NEST-roadmap#58]
As a continuation of https://github.com/insightsengineering/NEST-roadmap/issues/9

Our objective is to ease the starting point for the app developer to have a tool which initializes app directory.
Preferably, directory should contain:
1. app.R file with dummy data (scda), teal::init with single module. Each part of the code in app.R should have a comment explaining the section
2. Please research if making a new rhino project can be customized to include more modules into app.R. Customized means that during project initialization we would like to pick up modules from teal.marketplace and include them in the project being initialized (see the design of https://github.com/insightsengineering/NEST-roadmap/issues/9) 
3. Please research how we can customize app.R after initializing the project.

**Comment by nikolas-burkoff** [comment]
Rhino https://cran.r-project.org/web/packages/rhino/index.html

**Comment by nikolas-burkoff** [comment]
So I believe we are **not** able to use Rhino.

The reason for this is apps developed with Rhino cannot use R's standard way of referring to functions (i.e. with `library()` or with `::` or `source()`) but must use [box](https://klmr.me/box/) this is a completely different way of managing dependencies - it's much more like python modules.

I do not believe we should be forcing (possibly quite new) teal application developers to learn a whole new (and very niche) way of importing functions and packages. 

Outside of `teal`, rhino (together with box) do look like a good way to structure shiny apps with good support for js, CI/CD etc. in built.

There are things we can learn from rhino e.g. they have created a new project type:
![image](https://user-images.githubusercontent.com/15201933/180157712-df427613-f26a-4ec1-b4b3-41b3e9bf2462.png)
 which is something we may well want to do see https://github.com/insightsengineering/NEST-roadmap/issues/59
