### ISSUE TITLE
Research Rstudio tools for teal skeleton

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/NEST-roadmap#59]
Our objective is to ease the starting point for the app developer to have a tool which initializes app directory.
Preferably, directory should contain:

1. app.R file with dummy data (scda), teal::init with single module. Each part of the code in app.R should have a comment explaining the section
2. We would like to customize the app.R file by adding (using gui) more modules from teal.marketplace

See Rstudio templates and Rstudio addins for more
https://rstudio.github.io/rstudio-extensions/rstudio_project_templates.html
http://rstudio.github.io/rstudioaddins/

**Comment by nikolas-burkoff** [comment]
So this looks pretty easy to do (creating a new rstuido project) and I would actually put a couple files inside teal itself rather than in a new package for this - I'll come up with a dummy PR to show you what can be done

**Comment by nikolas-burkoff** [comment]
https://github.com/insightsengineering/teal/pull/701 is a draft PR (not to be merged) which shows this working and see that PR for more comments
