### ISSUE TITLE
Report generator enhancement

### ISSUE THREAD

**Issue by kumamiao** [insightsengineering/NEST-roadmap#68]
This is a continuation of enhancement for https://github.com/insightsengineering/NEST-roadmap/issues/11

High priorities for PI#5:
* [x] https://github.com/insightsengineering/teal.reporter/issues/142
* [x] https://github.com/insightsengineering/teal.reporter/issues/131
* [x] https://github.com/insightsengineering/teal.reporter/issues/137
* [x] https://github.com/insightsengineering/teal.reporter/issues/94
* [x] https://github.com/insightsengineering/teal.reporter/issues/130
* [x] https://github.com/insightsengineering/teal.reporter/issues/85

Medium priorities for PI#5:
* [ ] ~~https://github.com/insightsengineering/teal.reporter/issues/41~~
* [x] https://github.com/insightsengineering/teal.reporter/issues/53
* [x] https://github.com/insightsengineering/teal.reporter/issues/26

Low priorities for PI#5:
* [ ] ~~https://github.com/insightsengineering/teal.reporter/issues/35~~
* [ ] ~~https://github.com/insightsengineering/teal.reporter/issues/147~~
* [ ] ~~https://github.com/insightsengineering/teal.reporter/issues/150~~

**Comment by donyunardi** [comment]
Move item items to insightsengineering/nestdevs-tasks#4
Closing
