### ISSUE TITLE
title & footnote

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/NEST-roadmap#7]
- [x] https://github.com/insightsengineering/coredev-tasks/issues/361
- [x] https://github.com/insightsengineering/teal.modules.general/issues/231
- [x] https://github.com/insightsengineering/teal.modules.general/issues/252
- [x] https://github.com/insightsengineering/teal.modules.clinical/issues/210
- ~~https://github.com/insightsengineering/teal.goshawk/issues/110~~
- ~~https://github.com/insightsengineering/teal.osprey/issues/101~~

**Comment by donyunardi** [comment]
Continue with #75.
Closing.
