### ISSUE TITLE
Bootstrap fixes and enhancement

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/NEST-roadmap#72]
### Summary
Bootstrap feature was introduced with teal version 0.12.0 release. 
We identified issue during UAT and got feedback from opportunity for improvement.

### Issues to address:
* https://github.com/insightsengineering/coredev-tasks/issues/397
* https://github.com/insightsengineering/teal.slice/issues/147
* https://github.com/insightsengineering/teal/issues/738
* ~~https://github.com/insightsengineering/teal/issues/762~~
* ~~https://github.com/insightsengineering/teal/issues/735~~

**Comment by asbates** [comment]
Can I suggest insightsengineering/teal/issues/735 also
