### ISSUE TITLE
NEST technical blueprint

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/NEST-roadmap#78]
The goal is to create a learning material that explains some key concepts of `teal`. 

This is aimed to be used in the presentations/conferences (be able to put into the slides), as a learning material for new joiners, public NEST / pharmaverse website etc.

Ideally this should be:
- editable - to be able to introduce changes due to refactor
- automatically generated / testable - to keep this always up to date
- minimal - super-detailed is very likely to be outdated quickly (but please also see above)
- open - does not rely on any of Roche internal tools, systems etc.
- includes references to more detailed materials for better navigation

You are free to pick up the technology (e.g. quarto / markdown / diagrams).

The scope includes but is not limited to:
- 5Ws (Who? What? When? Where? Why)
  - Who are the main actors? I.e. app user, app developer, statistical programmer
- the concept of modules and encapsulation
- the concept of filter panel
- the concept of qenv
- the concept of DDL
- data flow throughout the application
- teal child packages and the relationships (i.e. dependencies) between then

Pawel's draft (feel free to reuse): https://app.diagrams.net/#G1QglX_J6aIG9LBcZfsLGBWyoOOmrldQt8

**Comment by donyunardi** [comment]
Definition of Done:
* Create a learning material that explains some key concepts of teal
* App developer should have a good overview knowledge of teal packages and its connection in NEST space.

**Comment by donyunardi** [comment]
### Tasks
* Decide on technology 
*

**Comment by donyunardi** [comment]
DRAFT: https://unardid.pages.roche.com/tealdevguide/
