### ISSUE TITLE
Improve UI of filer panel (3)

### ISSUE THREAD

**Issue by lcd2yyz** [insightsengineering/NEST-roadmap#81]
Filter panel re-design continued from https://github.com/insightsengineering/NEST-roadmap/issues/46

Through the research and design work in the past two increments, and gathering comments/feedback from expert users and key stakeholders, we converged on a design to move forward with. 

Wireframe: https://drive.google.com/file/d/1jxh0AoFu7-w-zZ6s3ZqawaMRiAYIBV-A/view?usp=sharing
Design diagrams: https://drive.google.com/file/d/1KoF3esaRBo4lNbOsYzPk983XtSZbw-fL/view?usp=sharing
Prototype Discussion: https://docs.google.com/document/d/1rxnqYsjTfgl7Ift2IpD4SXUlpo0bHc1ie15O0JGzUWk/edit

Following are the list of issues identified on the implementation level: 
https://github.com/insightsengineering/teal.slice/milestone/1

- [x] https://github.com/insightsengineering/teal.slice/issues/14
- [x] https://github.com/insightsengineering/teal.slice/issues/47
- [x] https://github.com/insightsengineering/teal.slice/issues/129
- [x] https://github.com/insightsengineering/teal.slice/issues/131
- [x] https://github.com/insightsengineering/teal.slice/issues/134
- [x] https://github.com/insightsengineering/teal.slice/issues/138
- [x] https://github.com/insightsengineering/teal.slice/issues/15
- [x] https://github.com/insightsengineering/teal.slice/issues/6
- [x] https://github.com/insightsengineering/teal.slice/issues/140
- [x] https://github.com/insightsengineering/teal.slice/issues/142
- [ ] ~~https://github.com/insightsengineering/teal.slice/issues/135~~
- [ ] ~~https://github.com/insightsengineering/teal.slice/issues/137~~
- [ ] ~~https://github.com/insightsengineering/teal.slice/issues/141~~
- [ ] ~~https://github.com/insightsengineering/teal.slice/issues/143~~
- [ ] ~~https://github.com/insightsengineering/teal.slice/issues/187~~
- [ ] ~~https://github.com/insightsengineering/teal.slice/issues/133~~
- [ ] ~~https://github.com/insightsengineering/teal.slice/issues/130~~
- [ ] ~~https://github.com/insightsengineering/teal.slice/issues/132~~

**Comment by donyunardi** [comment]
Moving to insightsengineering/nestdevs-tasks#6
