### ISSUE TITLE
Plan for `teal` release on CRAN (Part 1)

### ISSUE THREAD

**Issue by lcd2yyz** [insightsengineering/NEST-roadmap#85]
### Summary
Not committing to a release timeline, but research and plan out the steps needed
- review previous preparation work
- to release `teal` and family product on CRAN
- discuss possibility of releasing `tealverse`, similar to `tidyverse` that can install/load multiple teal and related module packages in one single step
- discuss potential release timeline

### Previous issues 
* https://github.com/insightsengineering/coredev-tasks/issues/334
* https://github.com/insightsengineering/coredev-tasks/issues/367 (this could be a duplicate and can be closed)

### Tasks
- What is the justification to move things to CRAN?
- When is the right time to publish to CRAN because things are still changing?
- [x] insightsengineering/nestdevs-tasks#13
~- [ ] insightsengineering/nestdevs-tasks#10~
~- [ ] insightsengineering/nestdevs-tasks#1~
~- [ ] Remove all soft-deprecated functions from products (i.e. `chunks` in teal)~
~- [ ] insightsengineering/nestdevs-tasks#11~
~- [ ] Add `--as-cran` in CICD and rerun pipeline~
~- [ ] Run autovalidateR on all teal packages~
~- [ ] Fix any R CMD Check Errors/Warnings/Notes from `--as-cran` setup and autovalidateR~
~- [ ] Discuss and decide whether we want to do `tealverse`~

**Comment by telepath37** [comment]
Suggest to prioritize this for upcoming PI (Jun 2023). Even with the ongoing filter panel redesign work, I think we should start putting a timeline on the release to CRAN for teal (or `tealverse`). Hopefully teal will be available on CRAN around Q3/4 this year.

**Comment by lcd2yyz** [comment]
Closing the issue for this increment.
Continue all open tasks in https://github.com/insightsengineering/nestdevs-tasks/issues/28
